apiVersion: apps/v1
kind: Deployment

metadata:
  name: web-deployment

spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: customer-app
    spec:
      containers:
        - name: customer-app-container
          image: user-customer-k8s:v1
          ports:
          - containerPort: 80
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: '6379'
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_USER
              value: hello_flask
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DB
              value: hello_flask_db
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD

  selector:
    matchLabels:
      component: customer-app